# https://angular.dev/tools/cli/deployment#manual-deployment-to-a-remote-server

ARG NODE_VERSION=20.17.0

FROM node:${NODE_VERSION}-alpine AS build

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci
COPY . .
RUN npx ng build --configuration production

FROM nginx:alpine

COPY --from=build /usr/src/app/dist/propinq-frontend/browser /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

